# Generated by Django 5.1.4 on 2025-01-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('converted', 'converted'), ('rejected', 'rejected')], default='new', max_length=100)),
                ('source', models.CharField(choices=[('online', 'online'), ('referral', 'referral'), ('event', 'event'), ('advertisement', 'advertisement')], default='online', max_length=100)),
            ],
        ),
    ]
